global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot 애플리케이션 모니터링
  - job_name: 'hhplus-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 5s
    scrape_timeout: 5s

  # 시스템 메트릭 (node_exporter가 있다면)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL 메트릭 (mysqld_exporter가 있다면)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Redis 메트릭 (redis_exporter가 있다면)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
